export const DELETE_EVENT = 'DELETE_EVENT'
export const CREATE_EVENT = 'CREATE_EVENT'
export const DELETE_ALL_EVENTS = 'DELETE_ALL_EVENTS'

// ログを追加
// 全ての操作ログを削除
export const ADD_OPERATION_LOG = 'ADD_OPERATION_LOG'
export const DELETE_ALL_OPERATION_LOGS = 'DELETE_ALL_OPERATION_LOGS'